
add_definitions(-DIMGUI_IMPL_OPENGL_LOADER_GLEW)
#ADD_DEFINITIONS(-DNBLAS -DUSE_GKREGEX)
#
#
#add_definitions(-DENGINE_DIRECTORY="${PROJECT_SOURCE_DIR}" -DSHADER_INCLUDE_DIRECTORY="${BGFX_DIR}/src")
#
